# Generated by Django 4.2.25 on 2025-12-08 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealitem',
            options={'ordering': ['day', 'meal_type']},
        ),
        migrations.AddField(
            model_name='mealitem',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
