# Generated by Django 4.2.25 on 2025-12-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_mealitem_options_mealitem_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='plan_json',
            field=models.JSONField(default=dict),
        ),
    ]
