# Generated by Django 4.2.25 on 2025-12-06 22:04

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('completed_exercises', models.JSONField(blank=True, default=list)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workout Plan', 'verbose_name_plural': 'Workout Plans'},
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='completed_exercises',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(choices=[('lose', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain', 'Gain Muscle')], default='maintain', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='total_completed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='plan_json',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['user', 'is_active'], name='workouts_wo_user_id_cba3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['user', 'created_at'], name='workouts_wo_user_id_a4981b_idx'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workouts.workoutplan'),
        ),
    ]
