# Generated by Django 4.2.25 on 2025-12-06 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_workoutsession_alter_workoutplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='workout_plan',
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='workoutplan',
            name='workouts_wo_user_id_cba3a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='workoutplan',
            name='workouts_wo_user_id_a4981b_idx',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='completed_exercises',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='total_completed_time',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='plan_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WorkoutSession',
        ),
    ]
