# Generated by Django 4.2.25 on 2025-12-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_exerciselog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseLog',
        ),
    ]
