# Generated by Django 4.2.25 on 2025-12-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0005_delete_exerciselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=100)),
                ('exercise_name', models.CharField(max_length=200)),
                ('exercise_data', models.JSONField(default=dict)),
                ('workout_day', models.IntegerField()),
                ('workout_date', models.DateField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'exercise_id', 'workout_date')},
            },
        ),
    ]
