# Generated by Django 4.2.25 on 2025-12-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_completedexercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedExercise',
        ),
    ]
