# Generated by Django 4.2.25 on 2025-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_ingredient_carbs_ingredient_fat_ingredient_protein_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=100),
        ),
    ]
