# Generated by Django 4.2.25 on 2025-12-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workout_day_streak',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive days with 6+ exercises completed'),
        ),
    ]
