MEALS = {
    "breakfast": {
        "lose": [
            {"name": "Smoothie bowl", "cal": 250, "protein": 15, "carbs": 40, "fat": 5},
            {"name": "Omelette + vegetables", "cal": 220, "protein": 18, "carbs": 8, "fat": 14},
            {"name": "Greek yogurt + fruits", "cal": 180, "protein": 12, "carbs": 25, "fat": 3},
            {"name": "Avocado toast", "cal": 230, "protein": 8, "carbs": 25, "fat": 12},
            {"name": "Protein pancakes", "cal": 210, "protein": 20, "carbs": 25, "fat": 4},
            {"name": "Chia pudding", "cal": 190, "protein": 6, "carbs": 20, "fat": 10},
            {"name": "Fruit salad + cottage cheese", "cal": 200, "protein": 15, "carbs": 25, "fat": 3},
        ],
        "maintain": [
            {"name": "Oats + banana + nuts", "cal": 350, "protein": 12, "carbs": 55, "fat": 10},
            {"name": "Egg sandwich", "cal": 380, "protein": 20, "carbs": 35, "fat": 16},
            {"name": "Peanut butter toast", "cal": 320, "protein": 12, "carbs": 30, "fat": 18},
            {"name": "Breakfast burrito", "cal": 360, "protein": 18, "carbs": 40, "fat": 14},
            {"name": "French toast", "cal": 340, "protein": 15, "carbs": 45, "fat": 10},
            {"name": "Bagel + cream cheese", "cal": 330, "protein": 10, "carbs": 45, "fat": 12},
            {"name": "Smoothie + granola", "cal": 350, "protein": 15, "carbs": 50, "fat": 8},
        ],
        "gain": [
            {"name": "Oats + peanut butter + milk", "cal": 500, "protein": 20, "carbs": 60, "fat": 20},
            {"name": "Eggs + cheese + toast", "cal": 550, "protein": 25, "carbs": 45, "fat": 28},
            {"name": "Protein shake + oats", "cal": 600, "protein": 35, "carbs": 70, "fat": 15},
            {"name": "Breakfast skillet", "cal": 580, "protein": 30, "carbs": 40, "fat": 32},
            {"name": "Pancakes + syrup + bacon", "cal": 620, "protein": 18, "carbs": 85, "fat": 22},
            {"name": "Full English breakfast", "cal": 650, "protein": 35, "carbs": 45, "fat": 38},
            {"name": "Protein waffles", "cal": 570, "protein": 30, "carbs": 60, "fat": 18},
        ],
    },
    "lunch": {
        "lose": [
            {"name": "Chicken salad", "cal": 300, "protein": 35, "carbs": 15, "fat": 12},
            {"name": "Tuna bowl", "cal": 280, "protein": 32, "carbs": 20, "fat": 8},
            {"name": "Veggie pasta", "cal": 260, "protein": 10, "carbs": 45, "fat": 6},
            {"name": "Quinoa salad", "cal": 270, "protein": 12, "carbs": 40, "fat": 7},
            {"name": "Turkey wrap", "cal": 290, "protein": 25, "carbs": 30, "fat": 10},
            {"name": "Lentil soup", "cal": 250, "protein": 15, "carbs": 35, "fat": 5},
            {"name": "Grilled chicken + veggies", "cal": 310, "protein": 40, "carbs": 20, "fat": 8},
        ],
        "maintain": [
            {"name": "Rice + chicken + veggies", "cal": 450, "protein": 35, "carbs": 50, "fat": 12},
            {"name": "Pasta + tuna", "cal": 500, "protein": 30, "carbs": 65, "fat": 15},
            {"name": "Couscous + chicken", "cal": 420, "protein": 32, "carbs": 45, "fat": 10},
            {"name": "Burrito bowl", "cal": 480, "protein": 28, "carbs": 55, "fat": 16},
            {"name": "Chicken sandwich", "cal": 460, "protein": 30, "carbs": 45, "fat": 18},
            {"name": "Salmon + sweet potato", "cal": 470, "protein": 35, "carbs": 40, "fat": 20},
            {"name": "Beef stir-fry", "cal": 490, "protein": 40, "carbs": 35, "fat": 22},
        ],
        "gain": [
            {"name": "Pasta + chicken cream", "cal": 700, "protein": 40, "carbs": 85, "fat": 22},
            {"name": "Rice + salmon + sauce", "cal": 750, "protein": 45, "carbs": 80, "fat": 28},
            {"name": "Burger maison + fries", "cal": 800, "protein": 35, "carbs": 90, "fat": 35},
            {"name": "Chicken alfredo pasta", "cal": 780, "protein": 42, "carbs": 75, "fat": 32},
            {"name": "Beef rice bowl", "cal": 720, "protein": 50, "carbs": 70, "fat": 25},
            {"name": "Pizza slice + salad", "cal": 760, "protein": 30, "carbs": 95, "fat": 28},
            {"name": "Steak + mashed potatoes", "cal": 820, "protein": 55, "carbs": 65, "fat": 38},
        ],
    },
    "dinner": {
        "lose": [
            {"name": "Vegetable soup", "cal": 180, "protein": 8, "carbs": 25, "fat": 5},
            {"name": "Grilled fish + salad", "cal": 220, "protein": 30, "carbs": 10, "fat": 8},
            {"name": "Omelette + salad", "cal": 200, "protein": 18, "carbs": 8, "fat": 12},
            {"name": "Stuffed peppers", "cal": 190, "protein": 12, "carbs": 20, "fat": 7},
            {"name": "Zucchini noodles + shrimp", "cal": 210, "protein": 25, "carbs": 15, "fat": 6},
            {"name": "Chicken vegetable stew", "cal": 195, "protein": 22, "carbs": 18, "fat": 5},
            {"name": "Baked salmon + asparagus", "cal": 230, "protein": 28, "carbs": 8, "fat": 10},
        ],
        "maintain": [
            {"name": "Rice + tuna + salad", "cal": 350, "protein": 30, "carbs": 35, "fat": 10},
            {"name": "Chicken sandwich", "cal": 380, "protein": 25, "carbs": 40, "fat": 14},
            {"name": "Pasta + vegetables", "cal": 360, "protein": 15, "carbs": 55, "fat": 8},
            {"name": "Fish tacos", "cal": 370, "protein": 28, "carbs": 35, "fat": 12},
            {"name": "Chicken curry + rice", "cal": 390, "protein": 32, "carbs": 40, "fat": 12},
            {"name": "Vegetable lasagna", "cal": 365, "protein": 20, "carbs": 45, "fat": 10},
            {"name": "Pork chops + veggies", "cal": 375, "protein": 35, "carbs": 20, "fat": 15},
        ],
        "gain": [
            {"name": "Rice + beef + cheese", "cal": 650, "protein": 45, "carbs": 60, "fat": 25},
            {"name": "Chicken wrap + fries", "cal": 680, "protein": 40, "carbs": 70, "fat": 28},
            {"name": "Pasta + cream + cheese", "cal": 700, "protein": 25, "carbs": 85, "fat": 30},
            {"name": "Shepherd's pie", "cal": 720, "protein": 35, "carbs": 75, "fat": 32},
            {"name": "Meatloaf + potatoes", "cal": 690, "protein": 42, "carbs": 60, "fat": 30},
            {"name": "Chicken parmesan", "cal": 710, "protein": 48, "carbs": 55, "fat": 35},
            {"name": "Beef stroganoff", "cal": 730, "protein": 45, "carbs": 50, "fat": 38},
        ],
    }
}